package escuelaing.edu.co.infrastructure.analysis;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import escuelaing.edu.co.domain.model.QueryEntry;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import java.io.InputStream;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

/**
 * Reads the {@code queries.json} file generated by the Phase 1 annotation processor
 * and builds an in-memory {@code queryId → QueryEntry} map.
 *
 * <p>This map bridges Phase 1 (static instrumentation) and Phase 2 (dynamic capture):
 * it lets {@code SamplingFilter} look up {@code @Req} business rules without
 * re-parsing JSON on every query execution.</p>
 *
 * <p>The file is loaded from the classpath at {@code loadtest/queries.json}.
 * If not found, a warning is logged and the registry stays empty — capture
 * continues but without {@code @Req} rules.</p>
 */
@Component
public class QueryRegistryLoader {

    private static final Logger LOG = Logger.getLogger(QueryRegistryLoader.class.getName());
    private static final String QUERIES_JSON_PATH = "loadtest/queries.json";

    private final ObjectMapper mapper;
    private Map<String, QueryEntry> registry = Collections.emptyMap();

    public QueryRegistryLoader(ObjectMapper mapper) {
        this.mapper = mapper;
    }

    @PostConstruct
    public void load() {
        InputStream stream = getClass().getClassLoader().getResourceAsStream(QUERIES_JSON_PATH);
        if (stream == null) {
            LOG.warning("[QueryRegistryLoader] " + QUERIES_JSON_PATH +
                    " not found on classpath. SamplingFilter will operate without @Req rules.");
            return;
        }

        try {
            JsonNode root = mapper.readTree(stream);
            JsonNode queriesNode = root.path("queries");

            Map<String, QueryEntry> map = new HashMap<>();
            for (JsonNode q : queriesNode) {
                QueryEntry entry = QueryEntry.builder()
                        .queryId(q.path("queryId").asText())
                        .className(q.path("className").asText())
                        .methodName(q.path("methodName").asText())
                        .queryDescription(q.path("queryDescription").asText())
                        .hasReq(q.path("hasReq").asBoolean(false))
                        .maxResponseTimeMs(q.path("maxResponseTimeMs").asLong(1000L))
                        .priority(q.path("priority").asText("MEDIUM"))
                        .reqDescription(q.path("reqDescription").asText())
                        .allowPlanChange(q.path("allowPlanChange").asBoolean(true))
                        .build();
                map.put(entry.getQueryId(), entry);
            }

            this.registry = Collections.unmodifiableMap(map);
            LOG.info("[QueryRegistryLoader] Loaded " + registry.size() + " entries from " + QUERIES_JSON_PATH);

        } catch (Exception e) {
            LOG.severe("[QueryRegistryLoader] Failed to parse " + QUERIES_JSON_PATH + ": " + e.getMessage());
        }
    }

    public Map<String, QueryEntry> getRegistry() {
        return registry;
    }

    public QueryEntry get(String queryId) {
        return registry.get(queryId);
    }
}
